apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-flask
  template:
    metadata:
      labels:
        app: vuln-flask
    spec:
      containers:
      - name: vuln-flask
        image: vuln-flask
        ports:
        - containerPort: 5000
